### ISSUE TITLE
MessageDigest exception under high load

### ISSUE THREAD

**Issue by stikkos** [j5ik2o/akka-persistence-dynamodb#354]
Under high load, this exception is sporadically thrown:

``ERROR c.g.j.a.p.d.journal.DynamoDBJournal - occurred error
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -15 is negative
	at java.base/sun.security.provider.DigestBase.engineUpdate(DigestBase.java:118)
	at java.base/java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:613)
	at java.base/java.security.MessageDigest.update(MessageDigest.java:355)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:430)
	at com.github.j5ik2o.akka.persistence.dynamodb.journal.PartitionKeyResolver$Mod.resolve(PartitionKeyResolver.scala:46)
	at com.github.j5ik2o.akka.persistence.dynamodb.journal.dao.WriteJournalDaoImpl.$anonfun$singlePutJournalRowFlow$2(WriteJournalDaoImpl.scala:670)
	at com.github.j5ik2o.akka.persistence.dynamodb.journal.dao.WriteJournalDaoImpl.$anonfun$singlePutJournalRowFlow$2$adapted(WriteJournalDaoImpl.scala:669)``

Could this be related to https://bugs.openjdk.java.net/browse/JDK-8009635?

**Comment by stikkos** [comment]
Just realized this has been fixed in latest release. thank you
